AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple Flask application

Resources:
  FlaskFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaDynamoDBExecutionRole
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable

  SessionsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: Sessions
      AttributeDefinitions:
        - AttributeName: sessionid
          AttributeType: S
      KeySchema:
        - AttributeName: sessionid
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
